### PR TITLE
go.mod: update to OpenCensus-Proto v0.2.0

### PR DESCRIPTION
**Pull request by odeke-em**
Updated to OpenCensus-Proto v0.2.0 but also
ran `go mod tidy` too for a clean-up of old
resources.

### CODE REVIEW

**Comment by odeke-em** [comment]
>I think you'll need to fix a few backwards-incompatible changes in proto.

@songy23 roger that, I updated the Proto version as you did in https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/102

**Comment by odeke-em** [comment]
And some errors from that update
```shell
contrib.go.opencensus.io/exporter/ocagent
# contrib.go.opencensus.io/exporter/ocagent
./ocagent.go:297:35: cannot convert true (type untyped bool) to type "github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ConstantDecision
./ocagent.go:297:35: invalid operation: csamp.Decision == true (mismatched types "github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ConstantDecision and bool)
./transform_stats_to_metrics.go:53:3: unknown field 'Descriptor_' in struct literal of type "github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric
./transform_stats_to_metrics.go:59:45: undefined: "github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric_MetricDescriptor
./transform_stats_to_metrics.go:67:11: undefined: "github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric_MetricDescriptor
```

**Comment by songy23** [comment]
> And some errors from that update

Yes, those are the backwards-incompatible changes that I'm referring to (https://github.com/census-instrumentation/opencensus-proto/pull/184 and https://github.com/census-instrumentation/opencensus-proto/pull/182).

**Comment by songy23** [comment]
> ./ocagent.go:297:38: undefined: agenttracebp
./transform_stats_to_metrics.go:53:3: cannot use promoted field Descriptor in struct literal of type "github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric

Please fix.

**Comment by odeke-em** [comment]
@songy23 alright, just one left from OpenCensus-Proto
```shell
# github.com/census-instrumentation/opencensus-proto/gen-go/agent/common/v1
../../../../pkg/mod/github.com/census-instrumentation/opencensus-proto@v0.2.0/gen-go/agent/common/v1/common.pb.go:22:11: undefined: proto.ProtoPackageIsVersion3
# github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1
../../../../pkg/mod/github.com/census-instrumentation/opencensus-proto@v0.2.0/gen-go/resource/v1/resource.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
```

**Comment by songy23** [comment]
From what I saw the error is different (https://travis-ci.org/census-ecosystem/opencensus-go-exporter-ocagent/builds/505582131#L678):
```bash
# contrib.go.opencensus.io/exporter/ocagent_test [contrib.go.opencensus.io/exporter/ocagent.test]
./ocagent_test.go:57:47: cannot use true (type bool) as type "github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ConstantDecision in field value
./ocagent_test.go:85:47: cannot use false (type bool) as type "github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ConstantDecision in field value
```

> undefined: proto.ProtoPackageIsVersion3

This should be fixed as long as you used v1.3.0 for protobuf.

**Comment by odeke-em** [comment]
Thank you for the review @songy23!

**Comment by odeke-em** [comment]
I'll just publish a new version then we'll be gucci to go.

**Pull request merged**
